Feature/auth
Equipo-de-desarrollo-FCEN-UDEA/SIGA_FCEN pull request #58
Opened 2024-11-18 18:32 UTC by alwos19

2024-11-18 20:56 UTC, DavidTorres-sys requested changes
Intentar mandar PR mas cortos, y adjuntar descripcion

2024-11-18 20:56 UTC, DavidTorres-sys commented on .pre-commit-config.yaml
> -    -   id: trailing-whitespace
No modificar el pre-commit

2024-11-18 20:56 UTC, DavidTorres-sys commented on app/api/routes/v1/users/auth.py
> +from app.errors.base import BaseErrors
Eliminar imports que no se usan

2024-11-18 20:56 UTC, DavidTorres-sys commented on app/infraestructure/services/emails/render_templay.py
> +env = Environment(loader=file_loader)
Solucionar

2024-11-19 15:04 UTC, alwos19 commented on app/infraestructure/services/emails/render_templay.py
> +env = Environment(loader=file_loader)
Esto simplemente es una confiuración para verl los templeate de los email como van quedando, cuando todo este listo lo quitamos

2024-11-19 19:07 UTC, merged