📌 Update package inclusion in pyproject.toml to reflect new app structure
Equipo-de-desarrollo-FCEN-UDEA/SIGA_FCEN pull request #65
Opened 2024-11-21 16:00 UTC by DavidTorres-sys

2024-11-21 16:17 UTC, alwos19 approved these changes

2024-11-21 20:23 UTC, estebandurangov requested changes

2024-11-21 20:23 UTC, estebandurangov commented on app/schemas/application/type/commission.py
> +    id_postgres: UUID | None = None
usar id en lugar de id_postgres para evitar conflictos mas adelante

2024-11-22 15:06 UTC, DavidTorres-sys commented on app/schemas/application/type/commission.py
> +    id_postgres: UUID | None = None
Cambiado

2024-11-22 20:44 UTC, estebandurangov approved these changes

2024-11-24 19:54 UTC, merged